### PR TITLE
Add Laravel Nova 4 Support

### PR DESCRIPTION
**Pull request by mziraki**

### CODE REVIEW

**Comment by freekmurze** [comment]
Have you tested this? According the upgrade guide there could be more steps involved.

**Comment by mziraki** [comment]
@freekmurze yes I tested it in local environment and it works! there is no breaking changes!

**Comment by mziraki** [comment]
@freekmurze there is no front-end packaging and the back-end code does not break any upgrade guidline.

**Comment by mziraki** [comment]
@freekmurze CRUD works!
image
image
image

**Comment by freekmurze** [comment]
Thanks!

**Comment by ksassnowski** [comment]
This PR dropped support for Nova 3, which I'm not sure was intentional. This package should still work with Nova 3.0, right? I can open a PR to change this from `^4.0` to `^3.0|^4.0`.

**Comment by freekmurze** [comment]
Feel free to send a PR if you're 100% sure it works in Nova v3 👍

**Pull request merged**
